# Generated by Django 3.1.2 on 2020-10-21 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('secret', models.TextField(max_length=8192, verbose_name='Содержание секрета')),
                ('passphrase', models.CharField(max_length=64, verbose_name='Фраза-пропуск')),
                ('lifetime', models.FloatField(verbose_name='Lifetime, время жизни секрета')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрел ли секрет')),
            ],
        ),
    ]
