# Generated by Django 3.1.2 on 2020-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(max_length=8192)),
                ('passphrase', models.CharField(max_length=64)),
                ('lifetime', models.FloatField()),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
