# Generated by Django 3.1.2 on 2020-11-17 18:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 21, 39, 9, 18254), verbose_name='Дата окончания срока действия')),
                ('secret', models.TextField(max_length=3000, verbose_name='Содержание секрета')),
                ('passphrase', models.CharField(blank=True, max_length=64, verbose_name='Фраза-пропуск')),
                ('lifetime', models.IntegerField(verbose_name='Время жизни секрета, секунд')),
                ('preview_has_been_shown', models.BooleanField(default=False, verbose_name='Было ли показано превью для его создателя')),
            ],
        ),
    ]
