# Generated by Django 3.1.2 on 2020-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='passphrase',
            field=models.CharField(default='', max_length=64, verbose_name='Фраза-пропуск'),
        ),
    ]
