# Generated by Django 3.1.2 on 2020-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecret', '0002_auto_20201029_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='passphrase',
            field=models.CharField(max_length=64, verbose_name='Фраза-пропуск'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.TextField(max_length=3000, verbose_name='Содержание секрета'),
        ),
    ]
