# Generated by Django 3.1.2 on 2020-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecret', '0003_auto_20201029_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='passphrase',
            field=models.CharField(blank=True, max_length=64, verbose_name='Фраза-пропуск'),
        ),
    ]
